/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    unoptimized: true,
    minimumCacheTTL: 60 * 60 * 24 * 90,
    domains: ["api.bogutovo.croonus.com"],
  },
  env: {
    API_URL: process.env.API_URL,
    GTM_ID: process.env.GTM_ID,
    PAGINATION_LIMIT: process.env.PAGINATION_LIMIT,
    SHOW_CHECKOUT_SHIPPING_FORM: process.env.SHOW_CHECKOUT_SHIPPING_FORM,
    TELEPHONE: process.env.TELEPHONE,
  },
  redirects: async () => {
    return [
      {
        source: "/en/blog/women-thongs-everyday-wear-yes-or-no",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/spavacice.html",
        destination: "/zene/zenske-spavacice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/ves.html",
        destination: "/zene/zenski-donji-ves",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/product/muski-slip-8/",
        destination: "/muskarci/muske-slip-gace",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/pidzame.html",
        destination: "/zene/zenske-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/bade-mantili.html",
        destination: "/zene/zenski-bade-mantili",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-9.html",
        destination: "/muski-slip-1200-beli",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/bebi-dol.html",
        destination: "/zene/zenske-bebi-dol-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-wb.html",
        destination: "/muske-bokserice-1218-crne",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1356-pahulja.html",
        destination: "/muske-bokserice-1356-pahulja",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1487.html",
        destination: "/muske-bokserice-1487",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-7.html",
        destination: "/muske-slip-gace",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1356.html",
        destination: "/muske-bokserice-1356-dezen",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/deciji-muski-dugi-ves.html",
        destination: "/decaci/duge-gace-za-decake",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muska-bodi-majica-1204.html",
        destination: "/muska-bodi-majica-1204",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1319.html",
        destination: "/muske-bokserice-1319-bele",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1227.html",
        destination: "/muske-bokserice-1227",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/products/z-slip/",
        destination: "/muskarci/muske-slip-gace",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-bade-mantil.html",
        destination: "/muskarci/muski-bade-mantili",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-siva.html",
        destination: "/muske-bokserice-1466-pingvin",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-3.html",
        destination: "/muski-slip-1279-beli",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1356-irvas.html",
        destination: "/muske-bokserice-1356-irvas",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1466-s.html",
        destination: "/muske-bokserice-1466-sive",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1202.html",
        destination: "/muske-bokserice-1202-bele",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/naslovna/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/decija-zenska-atlet-majica-4079.html",
        destination: "/decija-zenska-atlet-majica-4079",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-kombinezon-2477.html",
        destination: "/zenski-kombinezon-2477",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-2.html",
        destination: "/muski-slip-1336",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/decija-majica-3340-3344.html",
        destination: "/decija-majica-3340-3344",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-30.html",
        destination: "/muske-bokserice-1324-dezen",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-zvezde.html",
        destination: "/muske-bokserice-1466-zvezde",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1225.html",
        destination: "/muske-bokserice-1225-plave",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1466.html",
        destination: "/muske-bokserice-1466-pingvin",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-10.html",
        destination: "/muski-slip-1103",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-1.html",
        destination: "/muski-slip-1337-beli",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-8.html",
        destination: "/muski-slip-1208-beli",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/deciji-muski-slip-1.html",
        destination: "/deciji-muski-slip-4437-4439",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-3-1-12413.html",
        destination: "/muski-slip-muski-slip-31-12413",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1201.html",
        destination: "/muske-bokserice-1201-bele",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-osnovne.html",
        destination: "/muskarci/muske-bokserice/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-6.html",
        destination: "/muske-bokserice-1225-plave",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1356-p.html",
        destination: "/muske-bokserice-1356-pahulja",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muskarci/pidzame.html",
        destination: "/muskarci/muske-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/lokacije",
        destination: "/lokacije",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muskarci.html",
        destination: "/muskarci",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/devojcice.html",
        destination: "/devojcice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/majice.html",
        destination: "/zene/zenske-majice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/decaci.html",
        destination: "/decaci",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/women/pajamas.html",
        destination: "/zene/zenske-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muskarci/majice.html",
        destination: "/muskarci/muske-majice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muskarci/bokserice.html",
        destination: "/muskarci/muske-bokserice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/women/underwear.html",
        destination: "/zene/zenski-donji-ves",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/home/",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/decaci/pidzame.html",
        destination: "/decaci/pidzame-za-decake",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/blog/women-thongs-everyday-wear-yes-or-no",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/devojcice/pidzame.html",
        destination: "/devojcice/pidzame-za-devojcice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/blog/four-reasons-why-you-should-wear-cotton-pajamas",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/spavacica-za-trudnice-i-dojilje-2159-lila.html",
        destination: "/spavacica-za-trudnice-i-dojilje-2159-lila",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/men/pajamas.html",
        destination: "/muskarci/muske-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/ogrtaci.html",
        destination: "/zene/zenski-ogrtaci",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenska-spavacica-bez.html",
        destination: "/zene/zenske-bebi-dol-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muskarci/slip.html",
        destination: "/muskarci/muske-slip-gace",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/outlet-rs.html",
        destination: "/outlet",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenske-bokserice-2318.html",
        destination: "/zenske-bokserice-2318-bele",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/women/nightgowns.html",
        destination: "/zene/zenske-spavacice",
        permanent: true,
        statusCode: 301,
      },
      {
        source:
          "/sr/blog/zenske-tange-svakodnevno-nosenje-da-ili-ne-vodic-za-kupovinu-tangi",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/ves-kompleti.html",
        destination: "/zene/zenski-donji-ves-kompleti",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muskarci/bade-mantili.html",
        destination: "/muskarci/muski-bade-mantili",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/nova-kolekcija.html",
        destination: "/zene/nova-kolekcija-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/devojcice/nova-kolekcija.html",
        destination: "/devojcice/nova-kolekcija-3",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/kombinezoni.html",
        destination: "/zene/zenski-kombinezoni-za-spavanje",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/blog/standard-100-oeko-teks",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/potkosulje.html",
        destination: "/zene/zenske-potkosulje",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muska-majica-bela.html",
        destination: "/muskarci/muske-majice/muska-majica-1104",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muska-pizamasa.html",
        destination: "/muskarci/muske-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/decaci/majice.html",
        destination: "/decaci/majice-za-decake",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muskarci/potkosulje.html",
        destination: "/muskarci/muske-potkosulje",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenska-spavacica-2220.html",
        destination: "/zenska-spavacica-2220-crvena",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/women/bathrobe.html",
        destination: "/zene/zenski-bade-mantili",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/brazilke.html",
        destination: "/zene/brazilke",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/contact",
        destination: "/kontakt",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/women/baby-dol.html",
        destination: "/zene/zenske-bebi-dol-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenska-pidzama-2225.html",
        destination: "/zenska-pidzama-2225-kajsija",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muska-bodi-majica-crna.html",
        destination: "/muska-bodi-majica-1392-crna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-bade-mantil-roze.html",
        destination: "/zene/zenski-bade-mantili",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/outlet-rs/zene-outlet.html",
        destination: "/outlet/zene-outlet",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/o_nama",
        destination: "/o-nama",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/decaci/nova-kolekcija.html",
        destination: "/devojcice/nova-kolekcija-3",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenska-majica.html",
        destination: "/zene/zenske-majice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-ves-tange-2079.html",
        destination: "/zenski-ves-tange-2079-bez",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-bade-mantil-2787-crno.html",
        destination: "/zenski-bade-mantil-2787-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-ves-2218.html",
        destination: "/zenski-ves-2218-crni",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muska-majica-kimono-crna.html",
        destination: "/muska-majica-kimono-1235-crna",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenska-pidzama-tirkizna.html",
        destination: "/zenska-pidzama-2270",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/blog/cetiri-razloga-zasto-treba-nositi-pamucnu-pidzamu",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muske-bokserice-1202.html",
        destination: "/muske-bokserice-1202",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muska-majica-okrugli-izraz.html",
        destination: "/muskarci/muske-majice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-bebi-dol-1497.html",
        destination: "/muski-bebi-dol-1497",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/devojcice/majice.html",
        destination: "/devojcice/majice-za-devojcice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-ves-komplet-2909.html",
        destination: "/zenski-ves-komplet-2909-crni",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zene/majice.html",
        destination: "/zene/zenske-majice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-dugi-ves-beli.html",
        destination: "/muski-dugi-ves-1101",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/decaci/bokserice.html",
        destination: "/decaci/bokserice-za-decake",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenska-pidzama-2513.html",
        destination: "/zenska-pidzama-2513-roze",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-1.html",
        destination: "/muskarci/muske-slip-gace",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-bebi-dol-2136.html",
        destination: "/zene/zenske-bebi-dol-pidzame",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-ogrtac-2133.html",
        destination: "/zenski-ogrtac-2133-5",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/blog/kako-kupiti-muske-bokserice-online",
        destination: "/",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-bebi-dol-2124.html",
        destination: "/zenski-bebi-dol-2124",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muski-slip-9.html",
        destination: "/muskarci/muske-slip-gace",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenska-letnja-pidzama-2137.html",
        destination: "/zenska-letnja-pidzama-2137",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/devojcice/ves-kompletici.html",
        destination: "/devojcice/komplet-donji-ves-za-devojcice",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-ves-2335.html",
        destination: "/zenski-ves-2335",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-bade-mantil-2787-srce.html",
        destination: "/zenski-bade-mantil-2787-4",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenska-spavacica-roze.html",
        destination: "/zenska-spavacica-2825-6",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-ves-2749.html",
        destination: "/zenski-ves-2749-beli",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muska-atlet-majica-1.html",
        destination: "/muska-atlet-majica-1102",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/en/locations",
        destination: "/lokacije",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/muska-podkosulja.html",
        destination: "/muskarci/muske-potkosulje",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/zenski-bebi-dol-2136-bez.html",
        destination: "/zenski-bebi-dol-2241-2",
        permanent: true,
        statusCode: 301,
      },
      {
        source: "/sr/spavacica-za-trudnice-i-dojilje-2159-zuta.html",
        destination: "/spavacica-za-trudnice-i-dojilje-2159-zuta",
        permanent: true,
        statusCode: 301,
      },
    ];
  },
};

export default nextConfig;
