"use client";
export * from "./product/gallery";
export * from "./product/basic-data";
export * from "./product/wishlist";
export * from "./product/product-breadcrumbs";
export * from "./product/variants";
export * from "./product/tabs";
export * from "./product/description";
export * from "./product/declaration";
export * from "./category/single-category";
export * from "./category/filters-mobile";
export * from "./category/filters";
export * from "./category/filter";
export * from "./category/category-products";
